export const urls: { [key: string]: string } = {
  TENANTS: "/tenants",
  SITES: "/sites",
  LOGIN: "/login",
  REGISTER: "/register",
  UNIT_TYPES: "/unit-types",
  AVAILABLE_UNITS: "/available-units",
  LEADGUESTS: "/lead-guests",
  BOOKING: "/booking",
  BOOKING_GROUPS: '/booking-groups',
  BOOKING_BY_ID: "/booking-by-id",
  PAYMENTS: "/payments",
  EXTRATYPES: "/extra-types",
  ARRIVALS: "/arrivals",
  DEPARTURES_BY_DATE: "/departures-by-date",
  CHECK_IN_GUEST: "/check-in-guest",
  CHECK_OUT_GUEST: "/check-out-guest",
  CHECK_IN_MANY_GUESTS: "/check-in-many-guests",
  CHECK_OUT_MANY_GUESTS: "/check-out-many-guests",
  FEECALCS: "/get-fee-calc",
  GUEST_TYPES: "/guest-types",
  EQUIPMENT_TYPES: "/equipment-types",
  USERS: "/users",
  STATS: "/stats",
  TOTAL_ON_SITE: "/total-on-site-now",
  TOTAL_PAYMENTS_TODAY: "/total-payments-today",
  TOTAL_ON_SITE_TONIGHT: "/total-on-site-tonight",
  PAYMENTS_BREAKDOWN_TODAY: "/payments-breakdown-today",
  UNCONFIRMED_BOOKINGS_COUNT: "/unconfirmed-bookings-count",
  UPDATE_BOOKING_LEAD_GUEST_EXISTING: "/update-booking-lead-guest-existing",
  UPDATE_BOOKING_LEAD_GUEST_NEW: "/update-booking-lead-guest-new",
  UPDATE_LEAD_GUEST: "/update-lead-guest",
  NEW_NOTE: "/new-note",
  NEW_SITE: "/new-site",
  UPDATE_RATES: "/update-rates",
};

export const BOOKING_STATUSES = {
  CONFIRMED: "CONFIRMED",
  UNCONFIRMED: "UNCONFIRMED",
  CANCELLED: "CANCELLED"
}