import { PrismaClient } from "@prisma/client";

export const urls: { [key: string]: string } = {
  TENANTS: "/tenants",
  SITES: "/sites",
  LOGIN: "/login",
  REGISTER: "/register",
  UNIT_TYPES: "/unit-types",
  AVAILABLE_UNITS: "/available-units",
  LEADGUESTS: "/lead-guests",
  VEHICLES: "/vehicles",
  PETS: "/pets",
  BOOKINGS: "/bookings",
  BOOKINGS_BY_SITE: "/bookings-by-site",
  BOOKINGS_BY_SITE_AND_DATE_RANGE: "/bookings-by-site-and-date-range",
  BOOKING_BY_ID: "/booking-by-id",
  NEW_BOOKING: "/new-booking",
  PAYMENTS: "/payments",
  EXTRATYPES: "/extra-types",
  ARRIVALS: "/arrivals",
  DEPARTURES_BY_DATE: "/departures-by-date",
  CHECK_IN_GUEST: "/check-in-guest",
  CHECK_OUT_GUEST: "/check-out-guest",
  CHECK_IN_MANY_GUESTS: "/check-in-many-guests",
  CHECK_OUT_MANY_GUESTS: "/check-out-many-guests",
  FEECALCS: "/get-fee-calc",
  GUEST_TYPES: "/guest-types",
  EQUIPMENT_TYPES: "/equipment-types",
  USERS: "/users",
  STATS: "/stats",
  TOTAL_ON_SITE: "/total-on-site-now",
  TOTAL_PAYMENTS_TODAY: "/total-payments-today",
  TOTAL_ON_SITE_TONIGHT: "/total-on-site-tonight",
  PAYMENTS_BREAKDOWN_TODAY: "/payments-breakdown-today",
  UPDATE_BOOKING_LEAD_GUEST_EXISTING: "/update-booking-lead-guest-existing",
  UPDATE_BOOKING_LEAD_GUEST_NEW: "/update-booking-lead-guest-new",
  UPDATE_LEAD_GUEST: "/update-lead-guest",
  NEW_NOTE: "/new-note",
  NEW_SITE: "/new-site",
  UPDATE_RATES: "/update-rates",
};
